### ISSUE TITLE
ERROR: Could not build wheels for maturin, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by mir134** [talss89/termux-home-assistant-installer#9]
Device: xiaomi13   MIUI 14.0.31
Android 13
Termux
curl -sL https://github.com/talss89/termux-home-assistant-installer/releases/download/v2023.4.4-alpha.3/remote-install.sh | bash

I got this error, how to fixed it?

`Collecting maturin
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f0/80/ca5bbd5fb9dc8833a97ec3b1ee94a2d712fd7835bf6d7d82495af3f8c549/maturin-1.2.3.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: maturin
  Building wheel for maturin (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for maturin (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      /data/data/com.termux/files/usr/tmp/pip-build-env-68v7uulq/overlay/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py:80: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
        corresp(dist, value, root_dir)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/maturin
      copying maturin/__init__.py -> build/lib.linux-aarch64-cpython-311/maturin
      copying maturin/__main__.py -> build/lib.linux-aarch64-cpython-311/maturin
      copying maturin/import_hook.py -> build/lib.linux-aarch64-cpython-311/maturin
      running egg_info
      creating maturin.egg-info
      writing maturin.egg-info/PKG-INFO
      writing dependency_links to maturin.egg-info/dependency_links.txt
      writing requirements to maturin.egg-info/requires.txt
      writing top-level names to maturin.egg-info/top_level.txt
      writing manifest file 'maturin.egg-info/SOURCES.txt'
      reading manifest file 'maturin.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.json' under directory 'src/python_interpreter'
      writing manifest file 'maturin.egg-info/SOURCES.txt'
      running build_ext
      running build_rust
      error: rustup could not choose a version of rustc to run, because one wasn't specified explicitly, and no default is configured.
      help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for maturin
Failed to build maturin
ERROR: Could not build wheels for maturin, which is required to install pyproject.toml-based projects
~ $ 
`

**Comment by mir134** [comment]
follow the error info and next error:
error: rustup could not choose a version of rustc to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.

~ $ rustup default stable
info: syncing channel updates for 'stable-aarch64-linux-android'
info: latest update on 2023-08-24, rust version 1.72.0 (5680fa18f 2023-08-23)
error: target 'aarch64-linux-android' not found in channel.  Perhaps check https://doc.rust-lang.org/nightly/rustc/platform-support.html for available targets

**Comment by mir134** [comment]
try this on a fresh Termux installation then got another error: 

Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wbnor6wf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wbnor6wf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wbnor6wf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wbnor6wf/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wbnor6wf/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wbnor6wf/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wbnor6wf/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wbnor6wf/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1001, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wbnor6wf/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wbnor6wf/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 318, in run
          self.find_sources()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-wbnor6wf/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
    
I

**Comment by mir134** [comment]
The final solution is to modify the termux-home-assistant.sh file. Change 'pip install homeassistant==2023.4.4' to 'pip install homeassistant==2023.9'. After that, run it again, and the installation will be successful.

**Comment by marvinjoa** [comment]
> The final solution is to modify the termux-home-assistant.sh file. Change 'pip install homeassistant==2023.4.4' to 'pip install homeassistant==2023.9'. After that, run it again, and the installation will be successful.

I ran into other issues during installation, but this actually got HASS working for me too. Thank you!
